### ISSUE TITLE
Fazer protótipo no Figma

### ISSUE THREAD

**Issue by Felipecaf2323** [Felipecaf2323/Os-Mosqueteiros-AS63C-2024.1#4]

**Comment by AntonioFontess** [comment]
https://www.figma.com/proto/YvlbH4roi3VTHLmnRDEGYY/Agenda-(Copy)?node-id=401-1035&node-type=FRAME&t=lkGW0QlrP5Nl7K4t-0&scaling=scale-down&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=0%3A3
